### ISSUE TITLE
make scalajs compiler version configurable

### ISSUE THREAD

**Issue by KIC** [gtache/scalajs-gradle#13]
some libraries like jquery for example (be.doeraene:scalajs-jquery_sjs0.6_2.11:0.9.1) are not compatible. so we might want to need to tweak the possible versions in the build file.

**Comment by MMaus** [comment]
Yeah, indeed this would be very great. It seems very straight forward, just let Utils.groovy read these values from e.g. some properties file. This would be a great enhancement!

**Comment by gtache** [comment]
Sadly, it doesn't seem to be as easy as that, because I have to keep the versions of the dependencies of the plugin and the project consistent (and I can't change the dependencies of the plugin when applying it).

I think the only solution would be to publish different versions of the plugin, and that's what I'm trying to do at the moment (it seems to be going well). Gradle isn't very accomodating though, as it doesn't allow cross-building for each scala / scalajs versions... So I wrote a script to do that, and we'll see how it goes.

I'll try to release it this weekend.

**Comment by gtache** [comment]
I just released the version 0.3.0 of the plugin, with two different versions (one for Scala 2.11, an other for Scala 2.12), check the readme to see the syntax used. I did not release one for Scala 2.10, because reflection changed from 2.10 to 2.11 (and I use that to discover the tests). If there are requests, I may look into finding an other way to make it 2.10 compatible.
If you have any particular request (specific version for example), feel free to let me know!
